libtraceevent: Changed angled brackets to double quotes
Certain build systems, such as bazel, are picky about angled brackets vs
double quotes.

the failure you see when building is:

In file included from src/event-parse.c:27:
src/event-utils.h:13:10: error: 'event-parse.h' file not found with
<angled> include; use "quotes" instead
 #include <event-parse.h>
         ^~~~~~~~~~~~~~~
         "event-parse.h"

Arguably -iquote is more correct within the library build, hence bazel
using it. The libtraceevent Makefile is using -I, hence this not being
a problem for others.

Link: https://lore.kernel.org/linux-trace-devel/20210617194326.2107129-2-cjense@google.com

Signed-off-by: Claire Jensen <cjense@google.com>
Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>